# Generated by Django 3.2.4 on 2021-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='posts',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
